language: bash

os: osx

install:
- brew install lynx
script: 
- echo "export TERM='xterm-color'" >> ~/.bash_profile
- echo "export PS1='\[\e[0;33m\]\u\[\e[0m\]@\[\e[0;32m\]\h\[\e[0m\]:\[\e[0;34m\]\w\[\e[0m\]\$'" >> ~/.bash_profile
- source ~/.bash_profile
- echo "Testing this on Mac OSX"
- echo -e "\e[31mHello World\e[0m"
