language: bash

sudo: required
dist: trusty

install:
- sudo apt-get install lynx

script: 
- bash validateLinks --report terminal --link https://stefanos1316.github.io/my_curriculum_vitae/index.html
