language: bash

sudo: required
dist: trusty

install:
- sudo apt-get install lynx mailutils
script: 
- bash validateLinks -l https://www.balab.aueb.gr/ -s
- git clone https://github.com/stefanos1316/courses
- bash validateLinks -d courses -r -s
