language: bash

sudo: required
dist: trusty

install:
- sudo apt-get install lynx

script: 
- bash validateLinks --report terminal --repository https://github.com/stefanos1316/my_curriculum_vitae.git
- echo "Done with testing1" |mail -s "[Travis-CI] Test" sgeorgiou@aueb.gr
