language: bash

os: osx

install:
- brew install lynx
script: 
- chmod +x validateLinks
- bash validateLinks -l https://www.balab.aueb.gr/ -s
- git clone https://github.com/stefanos1316/courses
- ls -l
- bash validateLinks -d courses/courses -r -s
- lynx https://www.facebook.com
